### ISSUE TITLE
Shall we create a "jupyter-vim" organization?

### ISSUE THREAD

**Issue by wmvanvliet** [broesler/jupyter-vim#6]
At some point, I forked from ivanov/vim-ipython, then this repo was forked from me. You cleaned everything up, doing such a good job that my branch now tracks this repo. People have raised issues and PRs on both my repo and this one. It's a bit of a mess.

How do you feel about creating a "jupyter-vim" github organization and work together in one repo?

**Comment by broesler** [comment]
I agree with that. I was looking into adding people as contributors, but obviously that makes more sense to operate under a single "official" organization. Do you want to take the lead on setting it up? Otherwise I can do it.

-Bernie

**Comment by wmvanvliet** [comment]
Ok, jupyter-vim/jupyter-vim is up and running. Is there a way to move our issues over to that place?

**Comment by tcmulcahy** [comment]
In theory, https://help.github.com/en/articles/transferring-an-issue-to-another-repository would do it though I don't see the transfer button myself. Perhaps only @broesler can see it since this is his repo?

**Comment by broesler** [comment]
It looks like I can only transfer an issue to one of my own personal repos, not the organization. I'm still reading into it.
