### ISSUE TITLE
jupyter-vim.txt contains duplicate *jupyter-vim* tag

### ISSUE THREAD

**Issue by tcmulcahy** [broesler/jupyter-vim#8]
This trips up help doc generation. The second instance should be *jupyter-vim-introduction*

**Comment by mesmerx** [comment]
i fixed this error doing rm ~/.vim/bundle/jupyter-vim/doc -Rvif   and then updating the Plugin(or reinstall if you not using vundle)

**Comment by tcmulcahy** [comment]
I see this is fixed by 4440d863f7d2f72228bd47450012353518b477aa - not sure why I had an outdated copy.
