### ISSUE TITLE
Document additional options for installing jupyter-vim

### ISSUE THREAD

**Issue by tcmulcahy** [broesler/jupyter-vim#9]
Vundle is very popular these days, so I think we should document it as an option. Recent versions of vim make manual installation a breeze, so I think we should document that as an option too. (See https://shapeshed.com/vim-packages/ for details)

**Comment by wmvanvliet** [comment]
It has been added to the `README.md` over at https://github.com/jupyter-vim/jupyter-vim (which will become the "official" repository)

**Comment by tcmulcahy** [comment]
Nice!
